en:
    site:
        faq:
            h1: Got questions? We've got answers.
            h2section: Frequently Asked Questions
            p1: Click on the questions below to see the answer, if you don't see your question submit it in the form below
            
            