#!/bin/bash

cd ~/commonplace/ && git fetch && git checkout origin/leftronic

script/remote_server/pull_environment
source ./.env

bundle exec rails runner KissmetricsDumpDownload.perform && bundle exec km_db_import km_dump
