#!/bin/bash

cd ~/commonplace/ && git fetch && git checkout origin/leftronic && bundle

script/remote_server/pull_environment
source ./.env

RAILS_ENV=remote_worker bundle exec rails runner KissmetricsDumpDownload.perform && bundle exec km_db_import km_dump
