embed_assets: off
template_extension: html.mustache
template_function: Mustache.template
template_namespace: CommonPlace.templates
#javascript_compressor: closure
s3_bucket: "commonplace-assets"
s3_access_key_id: <%= ENV["S3_KEY_ID"] %>
s3_secret_access_key: <%= ENV["S3_KEY_SECRET"] %>
s3_permission: public_read

ssl: true

stylesheets:
  administration:
    - public/stylesheets/administration.css
  application:
    - public/stylesheets/application.css
    - public/stylesheets/post_box.css
    - public/stylesheets/tour.css
    - public/stylesheets/feeds/delete.css
    - public/stylesheets/feeds/edit_owner.css
  ie:
    - public/stylesheets/ie.css
  internship:
    - public/stylesheets/internship.css
  starter_site:
    - public/stylesheets/starter_site.css


  main_page:
    - public/stylesheets/main_page.css

  group_page:
    - public/stylesheets/group_page.css


  feed_page:
    - public/stylesheets/feed_page.css

  new_feed_page:
    - public/stylesheets/feed_registration.css

  registration:
    - public/stylesheets/registration_page.css

  login_page:
    - public/stylesheets/login_page.css

javascripts:
  application:
    - public/javascripts/showdown.js
    - public/javascripts/jquery-1.6.1.js
    - public/javascripts/jquery-ui.js
    - public/javascripts/jquery/jquery.*.js
    - public/javascripts/jquery/underscore.js
    - public/javascripts/jquery/mustache.js
    - public/javascripts/jquery/json2.js
    - public/javascripts/jquery/backbone.js
    - public/javascripts/innershiv.js
    - public/javascripts/lib.js
    - public/javascripts/sharing.js
    - public/javascripts/gaAddons.js
    - public/main_page/app.js
    - public/main_page/views/*.js
    - public/main_page/models/*.js
    - public/main_page/text/*.js
    - public/javascripts/facebook.js
  templates:
    - public/main_page/templates/*.html.mustache

  feed_page:
    - public/vendor/showdown.js
    - public/vendor/jquery.js
    - public/vendor/jquery-ui.js
    - public/vendor/placeholder.js
    - public/vendor/time_ago_in_words.js
    - public/vendor/underscore.js
    - public/vendor/mustache.js
    - public/vendor/json2.js
    - public/vendor/backbone.js
    - public/vendor/autoresize.js
    - public/shared/app.js
    - public/shared/models.js
    - public/shared/views.js
    - public/feed_page/*.js

  feed_page_templates:
    - public/templates/shared/*.html.mustache
    - public/templates/feed_page/*.html.mustache


  feed_registration_page:
    - public/vendor/slugify.js
    - public/vendor/jquery.js
    - public/javascripts/jquery/jquery.Jcrop.min.js
    - public/javascripts/feed_registration.js

  group_page:
    - public/vendor/showdown.js
    - public/vendor/jquery.js
    - public/vendor/jquery-ui.js
    - public/vendor/underscore.js
    - public/vendor/mustache.js
    - public/vendor/json2.js
    - public/vendor/time_ago_in_words.js
    - public/vendor/backbone.js
    - public/vendor/placeholder.js
    - public/vendor/autoresize.js
    - public/shared/app.js
    - public/shared/models.js
    - public/shared/views.js
    - public/group_page/*.js

  group_page_templates:
    - public/templates/group_page/*.html.mustache
    - public/templates/shared/*.html.mustache

  jquery:
    - public/javascripts/jquery-1.6.1.js
    - public/javascripts/jquery-ui.js
  map:
    - public/javascripts/jquery/jquery.polygon-input.js
    - public/javascripts/maps.js
  faq:
    - public/javascripts/faq.js
  starter_site:
    - public/javascripts/starter_site/application.js
    - public/javascripts/starter_site/easing.js
    - public/javascripts/starter_site/bubbles.js
    - public/javascripts/starter_site/tabs.js
    - public/javascripts/starter_site/slideshow.js
    - public/javascripts/starter_site/scroll.js

  registration_page:
    - public/javascripts/jquery-1.6.1.js
    - public/javascripts/jquery/jquery.placeholder.js
    - public/javascripts/jquery/jquery.Jcrop.min.js
    - public/javascripts/registration_page.js

  login_page:
    - public/vendor/jquery.js
    - public/javascripts/login_page.js
