embed_assets: on
template_extension: html.mustache
template_function: Mustache.template
template_namespace: CommonPlace.templates
stylesheets:
  administration:
    - public/stylesheets/administration.css
  application:
    - public/stylesheets/application.css
  ie:
    - public/stylesheets/ie.css
  internship:
    - public/stylesheets/internship.css
  starter_site:
    - public/stylesheets/starter_site.css

javascripts:
  application:
      - public/templates/*.html.mustache
      - public/javascripts/jquery-1.6.1.js
      - public/javascripts/jquery-ui.js
      - public/javascripts/jquery/jquery.*.js
      - public/javascripts/jquery/underscore.js
      - public/javascripts/jquery/mustache.js
      - public/javascripts/jquery/json2.js
      - public/javascripts/jquery/backbone.js
      - public/javascripts/innershiv.js
      - public/javascripts/models.js
      - public/javascripts/views.js
      - public/javascripts/controllers.js
      - public/javascripts/app.js
      - public/javascripts/inlineform.js
      - public/javascripts/maps.js
      - public/javascripts/infobox.js
      - public/javascripts/accounts.js
      - public/javascripts/sharing.js
  jquery:
    - public/javascripts/jquery-1.4.3.js
    - public/javascripts/jquery-ui.js
  map:
    - public/javascripts/jquery/jquery.polygon-input.js
    - public/javascripts/maps.js
  faq:
    - public/javascripts/faq.js
  starter_site:
    - public/javascripts/starter_site/application.js
    - public/javascripts/starter_site/easing.js
    - public/javascripts/starter_site/bubbles.js
    - public/javascripts/starter_site/tabs.js
    - public/javascripts/starter_site/slideshow.js
    - public/javascripts/starter_site/scroll.js

