development:
  app_id: "179741908724938"
  app_secret: ""

staging:
  app_id: "***REMOVED***"
  app_secret: "***REMOVED***"

production:
  app_id: "170191166378346"
  app_secret: "7b685eda4296ea2c252d8bb721a4b372"
