adapter: postgresql
host: <%= ENV['KISSMETRICS_POSTGRESQL_HOST'] %>
database: <%= ENV['KISSMETRICS_POSTGRESQL_DATABASE'] %>
username: <%= ENV['KISSMETRICS_POSTGRESQL_USER'] %>
password: <%= ENV['KISSMETRICS_POSTGRESQL_PASSWORD'] %>
