adapter: mysql2
host: <%= ENV['KISSMETRICS_MYSQL_HOST'] %>
database: <%= ENV['KISSMETRICS_MYSQL_DATABASE'] %>
username: <%= ENV['KISSMETRICS_MYSQL_USER'] %>
password: <%= ENV['KISSMETRICS_MYSQL_PASSWORD'] %>
