development:
  host: <%= ENV['MONGOID_HOST'] || "localhost" %>
  port: <%= ENV['MONGOID_PORT'] || '27017' %>
  username: <%= ENV['MONGOID_USERNAME'] || '' %>
  password: <%= ENV['MONGOID_PASSWORD'] || '' %>
  database: <%= ENV['MONGOID_DATABASE'] || "commonplace_development" %>

test:
  host: <%= ENV['MONGOID_HOST'] || "localhost" %>
  port: <%= ENV['MONGOID_PORT'] || '27017' %>
  username: <%= ENV['MONGOID_USERNAME'] || '' %>
  password: <%= ENV['MONGOID_PASSWORD'] || '' %>
  database: <%= ENV['MONGOID_DATABASE'] || "commonplace_test" %>

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
