send_daily_digest:
  cron: "00 21 * * *"
  class: DailyDigestJob
  args:
  queue: daily_digest
  description: "Sends daily digest"

import_feeds_rss:
  cron: "00 * * * *"
  class: RSSImporter
  args:
  queue: rss_importer
  description: "Imports feed announcements from rss"

geolocate_data_points:
  cron: "0 0 * * *"
  class: AddressGeolocator
  args:
  queue: geolocation
  description: "Geolocates bulk entered data points from organizers"

generate_statistics:
  cron: "00 23 * * *"
  class: StatisticsAggregator
  args:
  queue: statistics
  description: "Aggregates community statistics"

reset_emails_sent:
  cron: "0 0 * * *"
  class: EmailCountResetter
  args:
  queue: database
  description: "Resets the email_count"

recalculate_cp_credits:
  cron: "0 * * * *"
  class: CpCreditsCalculator
  args:
  queue: credits
  description: "Checks for invalidated users and recalculates their CP Credits"

compute_statistics_csv:
  cron: "0 0 * * *"
  class: StatisticsCsvGenerator
  args:
  queue: statistics
  description: "Generates Excel files for stats"
