# NOTE: All times are in server time.

send_daily_digest: #cron job to send the daily bulletin
  cron: "45 11 * * *"
  class: DailyDigestJob
  args:
  queue: daily_digest
  description: "Sends daily digest"

import_feeds_rss:
  cron: "00 * * * *"
  class: RSSImporter
  args:
  queue: rss_importer
  description: "Imports feed announcements from rss"

reset_emails_sent:
  cron: "0 0 * * *"
  class: EmailCountResetter
  args:
  queue: database
  description: "Resets the email_count"

recalculate_cp_credits:
  cron: "0 * * * *"
  class: CpCreditsCalculator
  args:
  queue: credits
  description: "Checks for invalidated users and recalculates their CP Credits"

send_weekly_network_health_stats:
  cron: "0 0 * * 0"
  class: StatisticsNetworkHealthCsvGenerator
  args:
  queue: statistics
  description: "Sends out a weekly digest of network health statistics for board review"

send_monthly_network_health_stats:
  cron: "0 0 0 * *"
  class: StatisticsNetworkHealthCsvGeneratorMonthly
  args:
  queue: statistics
  description: "Sends out a monthly digest of network health statistics"

ping_geckoboard:
  cron: "0 0 * * *"
  class: GeckoBoardAnnouncer
  args:
  queue: statistics
  description: "Send some statistics to our dashboard"

flush_daily_statistics:
  cron: "0 0 * * *"
  class: DailyStatisticsClearer
  args:
  queue: statistics
  description: "Flush daily statistics from Redis"
