send_daily_digest:
  cron: "00 17 * * *"
  class: DailyDigestJob
  args:
  queue: daily_digest
  description: "Sends daily digest"

import_feeds_rss:
  cron: "0 * * * *"
  class: RSSImporter
  args:
  queue: rss_importer
  description: "Imports feed announcements from rss"

