# NOTE: All times are in server time.

send_daily_digest: #cron job to send the daily bulletin
  cron: "45 11 * * *"
  class: DailyDigestJob
  args:
  queue: daily_digest
  description: "Sends daily digest"

send_single_post_noon: #cron job to send the single post emails at 12pm EST
  cron: "45 15 * * *"
  class: SinglePostEmailJob
  args:
  queue: single_post
  description: "Sends single post email at 12pm EST"

send_single_post_five_pm: #cron job to send the single post emails at 5pm EST
  cron: "45 20 * * *"
  class: SinglePostEmailJob
  args:
  queue: single_post
  description: "Sends single post email at 5pm EST"

send_safety_announcement:
  cron: "00 06 * * *"
  class: SafetyAnnouncementJob
  args:
  queue: safety_announcement
  description: "Send a safety announcement"

import_feeds_rss:
  cron: "00 * * * *"
  class: RSSImporter
  args:
  queue: rss_importer
  description: "Imports feed announcements from rss"

reset_emails_sent:
  cron: "0 0 * * *"
  class: EmailCountResetter
  args:
  queue: database
  description: "Resets the email_count"

recalculate_cp_credits:
  cron: "0 * * * *"
  class: CpCreditsCalculator
  args:
  queue: credits
  description: "Checks for invalidated users and recalculates their CP Credits"

scale_up_for_daily_digest:
  cron: "30 11 * * *"
  class: HerokuResque::NotificationWorkerScaler
  args: 50
  queue: server_management
  description: "Ramps up available dynos for daily digest mailings"

scale_down_post_daily_digest:
  cron: "30 12 * * *"
  class: HerokuResque::NotificationWorkerScaler
  args: 2
  queue: server_management
  description: "Decreases used dynos after daily digest mailings"

send_weekly_network_health_stats:
  cron: "0 0 * * 0"
  class: StatisticsNetworkHealthCsvGenerator
  args:
  queue: statistics
  description: "Sends out a weekly digest of network health statistics for board review"

send_monthly_network_health_stats:
  cron: "0 0 0 * *"
  class: StatisticsNetworkHealthCsvGeneratorMonthly
  args:
  queue: statistics
  description: "Sends out a monthly digest of network health statistics"

load_daily_new_stories:
  cron: "0 4 * * *"
  class: LoadStories
  args:
  queue: daily_new_stories
  description: "Pull new news of a community every midnight"
