send_daily_digest:
  cron: "00 21 * * *"
  class: DailyDigestJob
  args:
  queue: daily_digest
  description: "Sends daily digest"

import_feeds_rss:
  cron: "0 * * * *"
  class: RSSImporter
  args:
  queue: rss_importer
  description: "Imports feed announcements from rss"

reply_based_email:
  cron: "30 09 * * 1"
  class: ReplyInviteJob
  args:
  queue: reply_based_invite
  description: "Sends out invitation to the users if they receive replies to their posts."
