send_weekly_bulletin:
  cron: "00 9 * * 4"
  class: WeeklyBulletinJob
  args: 
  queue: weekly_bulletin
  description: "Sends weekly bulletin to all users that want it."

send_daily_digest:
  cron: "00 17 * * *"
  class: DailyDigestJob
  args:
  queue: daily_digest
  description: "Sends daily digest"

import_feeds_rss:
  cron: "0 * * * *"
  class: RSSImporter
  args:
  queue: rss_importer
  description: "Imports feed announcements from rss"

import_twitter_posts:
  cron: "0 * * * *"
  class: TwitterImporter
  args: 
  queue: outside-data
  description: "This job imports posts from Twitter as TwitterAnnouncements daily at midnight"
