# NOTE: All times are in server time.

send_daily_digest: #cron job to send the daily bulletin
  cron: "45 11 * * *"
  class: DailyDigestJob
  args:
  queue: daily_digest
  description: "Sends daily digest"

import_feeds_rss:
  cron: "00 * * * *"
  class: RSSImporter
  args:
  queue: rss_importer
  description: "Imports feed announcements from rss"

reset_emails_sent:
  cron: "0 0 * * *"
  class: EmailCountResetter
  args:
  queue: database
  description: "Resets the email_count"
