require 'spec_helper'

describe RssImporter do
  context "given an RSS element from Feedburner" do
    it "strips the FeedFlare" do
      html = '<p class="MsoNormal" style="margin: 0in 0in 10pt;"><span lang="EN" style="line-height: 115%; font-family: &quot;Arial&quot;, &quot;sans-serif&quot;; font-size: 12pt; mso-bidi-font-size: 11.0pt; mso-ansi-language: EN;">LANSING \342\200\224 The state\'s popular Pure Michigan tourism campaign has gotten a $3 million boost from private-sector partners to support advertising this year.<br /><br />The Travel Michigan Ad Partnership Program announced Monday that the contributions from 28 communities and destinations in Michigan are double those from 2010. The Michigan Economic Development Corp. is matching those contributions.<br /><br />The Henry Ford in Dearborn and visitors bureaus in Traverse City and Mackinac Island are national sponsors, each contributing $500,000 toward the Pure Michigan national campaign. Travel Michigan says the money means ads will be able to run longer on cable television networks nationwide.<br /><br />Pure Michigan campaigns promote the state\'s beaches, golf courses and other destinations to potential tourists.<o:p></o:p></span></p><div class="feedflare">\n<a href="http://feeds.feedburner.com/~ff/LakeSuperiorCommunityPartnershipNews?a=TLKen1QI3lU:Xo_UPvx6M1s:yIl2AUoC8zA"><img src="http://feeds.feedburner.com/~ff/LakeSuperiorCommunityPartnershipNews?d=yIl2AUoC8zA" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LakeSuperiorCommunityPartnershipNews?a=TLKen1QI3lU:Xo_UPvx6M1s:V_sGLiPBpWU"><img src="http://feeds.feedburner.com/~ff/LakeSuperiorCommunityPartnershipNews?i=TLKen1QI3lU:Xo_UPvx6M1s:V_sGLiPBpWU" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LakeSuperiorCommunityPartnershipNews?a=TLKen1QI3lU:Xo_UPvx6M1s:qj6IDK7rITs"><img src="http://feeds.feedburner.com/~ff/LakeSuperiorCommunityPartnershipNews?d=qj6IDK7rITs" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LakeSuperiorCommunityPartnershipNews?a=TLKen1QI3lU:Xo_UPvx6M1s:l6gmwiTKsz0"><img src="http://feeds.feedburner.com/~ff/LakeSuperiorCommunityPartnershipNews?d=l6gmwiTKsz0" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LakeSuperiorCommunityPartnershipNews?a=TLKen1QI3lU:Xo_UPvx6M1s:gIN9vFwOqvQ"><img src="http://feeds.feedburner.com/~ff/LakeSuperiorCommunityPartnershipNews?i=TLKen1QI3lU:Xo_UPvx6M1s:gIN9vFwOqvQ" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LakeSuperiorCommunityPartnershipNews?a=TLKen1QI3lU:Xo_UPvx6M1s:TzevzKxY174"><img src="http://feeds.feedburner.com/~ff/LakeSuperiorCommunityPartnershipNews?d=TzevzKxY174" border="0"></img></a> <a href="http://feeds.feedburner.com/~ff/LakeSuperiorCommunityPartnershipNews?a=TLKen1QI3lU:Xo_UPvx6M1s:-BTjWOF_DHI"><img src="http://feeds.feedburner.com/~ff/LakeSuperiorCommunityPartnershipNews?i=TLKen1QI3lU:Xo_UPvx6M1s:-BTjWOF_DHI" border="0"></img></a>\n</div><img src="http://feeds.feedburner.com/~r/LakeSuperiorCommunityPartnershipNews/~4/TLKen1QI3lU" height="1" width="1"/>'
      intended_html = '<p class="MsoNormal" style="margin: 0in 0in 10pt;"><span lang="EN" style="line-height: 115%; font-family: "Arial", "sans-serif"; font-size: 12pt; mso-bidi-font-size: 11.0pt; mso-ansi-language: EN;">LANSING \342\200\224 The state\'s popular Pure Michigan tourism campaign has gotten a $3 million boost from private-sector partners to support advertising this year.<br /><br />The Travel Michigan Ad Partnership Program announced Monday that the contributions from 28 communities and destinations in Michigan are double those from 2010. The Michigan Economic Development Corp. is matching those contributions.<br /><br />The Henry Ford in Dearborn and visitors bureaus in Traverse City and Mackinac Island are national sponsors, each contributing $500,000 toward the Pure Michigan national campaign. Travel Michigan says the money means ads will be able to run longer on cable television networks nationwide.<br /><br />Pure Michigan campaigns promote the state\'s beaches, golf courses and other destinations to potential tourists.<o:p></o:p></span></p><img src="http://feeds.feedburner.com/~r/LakeSuperiorCommunityPartnershipNews/~4/TLKen1QI3lU" height="1" width="1"/>'

      RssImporter.strip_feedflare(html).should == intended_html
    end
  end

  context "given an Rss element from anywhere else" do
    it "should not modify the HTML" do
      html = '<p class="MsoNormal" style="margin: 0in 0in 10pt;"><span lang="EN" style="line-height: 115%; font-family: "Arial", "sans-serif"; font-size: 12pt; mso-bidi-font-size: 11.0pt; mso-ansi-language: EN;">LANSING \342\200\224 The state\'s popular Pure Michigan tourism campaign has gotten a $3 million boost from private-sector partners to support advertising this year.<br /><br />The Travel Michigan Ad Partnership Program announced Monday that the contributions from 28 communities and destinations in Michigan are double those from 2010. The Michigan Economic Development Corp. is matching those contributions.<br /><br />The Henry Ford in Dearborn and visitors bureaus in Traverse City and Mackinac Island are national sponsors, each contributing $500,000 toward the Pure Michigan national campaign. Travel Michigan says the money means ads will be able to run longer on cable television networks nationwide.<br /><br />Pure Michigan campaigns promote the state\'s beaches, golf courses and other destinations to potential tourists.<o:p></o:p></span></p><img src="http://feeds.feedburner.com/~r/LakeSuperiorCommunityPartnershipNews/~4/TLKen1QI3lU" height="1" width="1"/>'

      RssImporter.strip_feedflare(html).should == html
    end
  end

  context "given a markdown feed and an RSS source link" do
    it "should truncate the feed to 150 words and link to the source" do
      source = "http://en.wikipedia.org/wiki/Robert_D._Putnam"
      orig_feed  = 'Roger Putnam graduated from Swarthmore College in 1963, won a Fulbright Fellowship to study at Balliol College, Oxford, and went on to earn master\'s and doctorate degrees from Yale University, the latter in 1970. He taught at the University of Michigan until going to Harvard in 1979, where he has held a variety of positions, including Dean of the Kennedy School, and is currently the Malkin Professor of Public Policy. Putnam was born as a religiously observant Methodist. Around the time of his marriage, he converted to Judaism, his wife\'s religion. His first work in the area of social capital was Making Democracy Work: Civic Traditions in Modern Italy, a comparative study of regional governments in Italy which drew great scholarly attention for its argument that the success of democracies depends in large part on the horizontal bonds that make up social capital.In 1995 he published "Bowling Alone: America\'s Declining Social Capital" in the Journal of Democracy. The article was widely read and garnered much attention for Putnam, including an invitation to meet with then-President Bill Clinton and a spot in the pages of People magazine. Some critics argued that Putnam was ignoring new organizations and forms of social capital; others argued that many of the included organizations were responsible for the suppression of civil rights movements and the reinforcement of anti-egalitarian social norms. Over the last decade and a half, the United States had seen an increase in bowlers but a decrease in bowling leagues.'
      truncated = 'Roger Putnam graduated from Swarthmore College in 1963, won a Fulbright Fellowship to study at Balliol College, Oxford, and went on to earn master\'s and doctorate degrees from Yale University, the latter in 1970. He taught at the University of Michigan until going to Harvard in 1979, where he has held a variety of positions, including Dean of the Kennedy School, and is currently the Malkin Professor of Public Policy. Putnam was born as a religiously observant Methodist. Around the time of his marriage, he converted to Judaism, his wife\'s religion. His first work in the area of social capital was Making Democracy Work: Civic Traditions in Modern Italy, a comparative study of regional governments in Italy which drew great scholarly attention for its argument that the success of democracies depends in large part on the horizontal bonds that make up social capital.In 1995 he published "Bowling<a href="http://en.wikipedia.org/wiki/Robert_D._Putnam">...read more</a>' 

      RSSImporter.truncate_feed(orig_feed, source).should == truncated
     end
    end

  
end
